export const COLORS = {
  primary: '#1B5E20',
  primaryLight: '#4CAF50',
  primaryDark: '#0D3B0F',
  accent: '#FF6F00',
  bg: '#F5F5F5',
  card: '#FFFFFF',
  text: '#212121',
  textSecondary: '#757575',
  border: '#E0E0E0',
  success: '#4CAF50',
  warning: '#FF9800',
  danger: '#F44336',
  pxBadge: '#2E7D32',
  affiliate: '#BDBDBD',
};

export const styles = {
  container: {
    maxWidth: 480,
    margin: '0 auto',
    backgroundColor: COLORS.bg,
    minHeight: '100vh',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    paddingBottom: 20,
  },
  header: {
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.primaryLight} 100%)`,
    color: '#fff',
    padding: '20px 16px 16px',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  headerTitle: { fontSize: 20, fontWeight: 700, marginBottom: 4 },
  headerSub: { fontSize: 12, opacity: 0.85 },
  summaryCard: {
    margin: '12px 16px',
    padding: 16,
    backgroundColor: COLORS.card,
    borderRadius: 12,
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
  },
  summaryGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr', gap: 8, marginBottom: 12 },
  summaryItem: { textAlign: 'center' },
  summaryNumber: { fontSize: 22, fontWeight: 700, color: COLORS.primary },
  summaryLabel: { fontSize: 10, color: COLORS.textSecondary, marginTop: 2 },
  aiRecommend: {
    background: `linear-gradient(90deg, ${COLORS.primary}11, ${COLORS.primaryLight}11)`,
    borderRadius: 8,
    padding: '8px 12px',
    fontSize: 13,
    color: COLORS.primary,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  tabContainer: {
    display: 'flex',
    overflowX: 'auto',
    padding: '0 16px',
    gap: 8,
    marginBottom: 12,
    WebkitOverflowScrolling: 'touch',
    scrollbarWidth: 'none',
  },
  tab: (active) => ({
    padding: '8px 16px',
    borderRadius: 20,
    border: 'none',
    backgroundColor: active ? COLORS.primary : '#fff',
    color: active ? '#fff' : COLORS.text,
    fontSize: 13,
    fontWeight: active ? 600 : 400,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    boxShadow: active ? '0 2px 8px rgba(27,94,32,0.3)' : '0 1px 3px rgba(0,0,0,0.1)',
    transition: 'all 0.2s',
    flexShrink: 0,
  }),
  section: { margin: '0 16px 16px' },
  sectionTitle: {
    fontSize: 16, fontWeight: 700, marginBottom: 12, color: COLORS.text,
    display: 'flex', alignItems: 'center', gap: 8,
  },
  card: {
    backgroundColor: COLORS.card, borderRadius: 12, padding: 16, marginBottom: 12,
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  },
  productCard: {
    backgroundColor: COLORS.card, borderRadius: 12, padding: 14, marginBottom: 10,
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)', position: 'relative',
  },
  productName: { fontSize: 14, fontWeight: 600, marginBottom: 4 },
  productPrice: { fontSize: 16, fontWeight: 700, color: COLORS.accent },
  productDesc: { fontSize: 12, color: COLORS.textSecondary, marginTop: 4, lineHeight: 1.4 },
  pxBadge: {
    display: 'inline-block', backgroundColor: COLORS.pxBadge, color: '#fff',
    fontSize: 10, padding: '2px 6px', borderRadius: 4, fontWeight: 600, marginLeft: 6,
  },
  affiliateText: { position: 'absolute', bottom: 8, right: 10, fontSize: 9, color: COLORS.affiliate },
  buyButton: (color = COLORS.primary) => ({
    padding: '8px 14px', borderRadius: 8, border: 'none', backgroundColor: color,
    color: '#fff', fontSize: 12, fontWeight: 600, cursor: 'pointer', marginRight: 6, marginTop: 8,
  }),
  tagContainer: { display: 'flex', flexWrap: 'wrap', gap: 4, marginTop: 6 },
  tag: { fontSize: 10, padding: '2px 8px', borderRadius: 10, backgroundColor: `${COLORS.primary}15`, color: COLORS.primary },
  progressBar: () => ({ height: 8, borderRadius: 4, backgroundColor: '#E8F5E9', overflow: 'hidden', position: 'relative' }),
  progressFill: (pct, color = COLORS.primaryLight) => ({
    height: '100%', width: `${Math.min(pct, 100)}%`, backgroundColor: color,
    borderRadius: 4, transition: 'width 0.5s ease',
  }),
  input: {
    width: '100%', padding: '10px 12px', borderRadius: 8,
    border: `1px solid ${COLORS.border}`, fontSize: 14, boxSizing: 'border-box', marginBottom: 8,
  },
  checkbox: { marginRight: 6, accentColor: COLORS.primary },
  modal: {
    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center',
    justifyContent: 'center', zIndex: 1000, padding: 20,
  },
  modalContent: {
    backgroundColor: '#fff', borderRadius: 16, padding: 24, maxWidth: 400,
    width: '100%', maxHeight: '80vh', overflowY: 'auto',
  },
  reviewCard: {
    backgroundColor: COLORS.card, borderRadius: 12, padding: 14, marginBottom: 10,
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)', borderLeft: `3px solid ${COLORS.primary}`,
  },
  subTab: (active) => ({
    padding: '6px 12px', borderRadius: 16,
    border: `1px solid ${active ? COLORS.primary : COLORS.border}`,
    backgroundColor: active ? `${COLORS.primary}10` : '#fff',
    color: active ? COLORS.primary : COLORS.textSecondary,
    fontSize: 12, cursor: 'pointer', whiteSpace: 'nowrap',
  }),
  filterChip: (active) => ({
    padding: '6px 12px', borderRadius: 16, border: 'none',
    backgroundColor: active ? COLORS.primary : '#E8E8E8',
    color: active ? '#fff' : COLORS.text, fontSize: 12, cursor: 'pointer', whiteSpace: 'nowrap',
  }),
};
